!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        019DqP0P-FormsManager1:
          path: dataset/019DqP0P-FormsManager1
          prefix: Republic
          standardFeature: false
          versions:
            '1':
              modifiedDate: '2022-02-08 21:08:51'
        019DqP0P-Forms:
          path: dataset/019DqP0P-Forms
          prefix: ncino
          standardFeature: false
          versions:
            Fall 2019:
              modifiedDate: '2022-03-24 21:46:39'
